server:
  port: 8081
spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/inventory
    username: fibabanka
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always